Repository dailyco/legacy-happy-ending, pull requests merged in 2020-11, with the labels that each got.

#233 fix bgm error
  src/App.js
Labels: 🐞 BUG, 📄 Page

#235 Fix/selectionbox event listener
  src/scss/Atoms/Button.scss
  src/ui/Molecules/SelectionBox.js
Labels: ⚙️ Refactor, 🐞 BUG, 👷 Design, 📄 Page, 🧩 Component

#237 web-cam ratio 수정
  src/ui/Templates/SeparatedTemplate16_1.js
Labels: 🐞 BUG

#242 Feature/dev print
  package.json
  src/scss/Atoms/Span.scss
  src/scss/colors.scss
  src/scss/pages.scss
  src/ui/Molecules/DetailedButton.js
  src/ui/Pages/P25.js
  src/ui/Pages/P29.js
  src/ui/Pages/P5.js
  yarn.lock
Labels: ⚙️ Refactor, ✨ Feature, 👷 Design, 📄 Page

#243 console log del
  src/ui/Pages/P8_1.js
  src/ui/Pages/P8_1_2.js
  src/ui/Pages/P8_2_2.js
Labels: 🐞 BUG, 📄 Page

#244 p17 애니메이션 추가
  src/scss/animations.scss
  src/ui/Templates/SeparatedTemplate17.js
Labels: ✨ Feature, 📄 Page

#246 14P 텍스트 미 입력시 알려주고, 넘어가지 않게 수정 #245
  src/ui/Pages/P14.js
  src/ui/Templates/SeparatedTemplate14.js
  src/ui/reducerInputs.js
Labels: ✨ Feature, 🐞 BUG, 📄 Page

#248 14P validate error solved #247
  src/ui/Pages/P14.js
Labels: 🐞 BUG, 📄 Page

#252 p17 bug fix
  src/ui/Templates/SeparatedTemplate17.js
Labels: 🐞 BUG, 📄 Page, 🚨 ASAP

#253 p17 webcam 좌우반전 해결
  src/ui/Templates/SeparatedTemplate16_1.js
Labels: ✨ Feature, 📄 Page

#255 Feature/prevent click event fade in
  src/ui/Molecules/SelectionBox.js
  src/ui/Organisms/FullTextFieldResponse.js
  src/ui/Organisms/GraveStoneResponse.js
  src/ui/Organisms/InfoResponse.js
  src/ui/Organisms/MultiTextFieldResponse.js
  src/ui/Organisms/SingleTextFieldResponse.js
  src/ui/Pages/P10.js
  src/ui/Pages/P11.js
  src/ui/Pages/P12_1.js
  src/ui/Pages/P12_2.js
  src/ui/Pages/P13.js
  src/ui/Pages/P14.js
  src/ui/Pages/P16.js
  src/ui/Pages/P16_1.js
  src/ui/Pages/P17.js
  src/ui/Pages/P19.js
  src/ui/Pages/P2.js
  src/ui/Pages/P20.js
  src/ui/Pages/P21.js
  src/ui/Pages/P23.js
  src/ui/Pages/P24.js
  src/ui/Pages/P25.js
  src/ui/Pages/P26.js
  src/ui/Pages/P3.js
  src/ui/Pages/P4.js
  src/ui/Pages/P5.js
  src/ui/Pages/P6.js
  src/ui/Pages/P7.js
  src/ui/Pages/P7_1.js
  src/ui/Pages/P7_2.js
  src/ui/Pages/P8.js
  src/ui/Pages/P8_1.js
  src/ui/Pages/P8_1_1.js
  src/ui/Pages/P8_1_2.js
  src/ui/Pages/P8_2.js
  src/ui/Pages/P8_2_1.js
  src/ui/Pages/P8_2_2.js
  src/ui/Templates/SeparatedTemplate14.js
  src/ui/Templates/SeparatedTemplate16.js
  src/ui/Templates/SeparatedTemplate16_1.js
  src/ui/Templates/SeparatedTemplate17.js
  src/ui/Templates/SeparatedTemplate7.js
Labels: ✨ Feature, 📄 Page

#256 p29 애니메이션 구현완료
  src/scss/Templates/SeparatedTemplate29.scss
  src/scss/animations.scss
  src/ui/Molecules/Paragraph.js
  src/ui/Molecules/Title.js
  src/ui/Organisms/Decorations.js
  src/ui/Organisms/Paragraphs.js
  src/ui/Pages/P29.js
  src/ui/Templates/SeparatedTemplate29.js
Labels: 📄 Page, 🚨 ASAP

#257 국화 이름 제대로 안 나오는 버그 수정
  src/ui/Pages/P29.js
Labels: 🐞 BUG

#254 Edit text in sadman section
  src/ui/Pages/P29.js
Labels: 🐞 BUG, 🚨 ASAP

#258 fix bug
  src/ui/Templates/SeparatedTemplate7.js
Labels: 🐞 BUG

#259 이미지 튀어나옴 문제 해결
  src/scss/Templates/SeparatedTemplate29.scss
Labels: 🐞 BUG

#260 Feature/fix/bugs
  src/scss/Atoms/P.scss
  src/ui/Pages/P29.js
Labels: 🐞 BUG, 🚨 ASAP

#262 Feature/print layout
  public/index.html
  src/scss/pages.scss
  src/scss/print.scss
  src/ui/Pages/P29.js
Labels: ✨ Feature, 💅🏻 Design, 📄 Page

#263 code refactor
  src/scss/Atoms/H3.scss
  src/scss/Atoms/P.scss
  src/scss/style.scss
Labels: ⚙️ Refactor, 💅🏻 Design

#265 29P image overflow 문제 해결하기 #264
  src/assets/images/29p_images/29 1F.png
  src/assets/images/29p_images/29 3F.png
  src/assets/images/29p_images/29 4F.png
  src/assets/images/29p_images/29 5F.png
  src/assets/images/29p_images/29 ebook-letter.png
  src/scss/Templates/SeparatedTemplate29.scss
Labels: 🐞 BUG, 💅🏻 Design, 📄 Page

#266 29P image overflow 문제 해결하기 #264
  src/assets/images/29p_images/29 2F.png
  src/scss/Templates/SeparatedTemplate29.scss
Labels: ⚙️ Refactor, 💅🏻 Design, 📄 Page
